import SwiftUI

struct LoginView: View { @EnvironmentObject var store:AppStore; @State var email=""; @State var password=""; var body:some View { NavigationStack { VStack(spacing:22){ Spacer(); Image(systemName:"sparkles.rectangle.stack.fill").font(.system(size:64)).foregroundStyle(.tint); Text("NovaCoach").font(.largeTitle.bold()); Text("Sınava kadar ne yapacağını sen düşünme.").foregroundStyle(.secondary); TextField("E-posta",text:$email).textFieldStyle(.roundedBorder).textInputAutocapitalization(.never); SecureField("Şifre",text:$password).textFieldStyle(.roundedBorder); Button("Giriş Yap"){store.login(email:email,password:password)}.buttonStyle(.borderedProminent).controlSize(.large); Spacer() }.padding(24) } } }

struct OnboardingView: View { @EnvironmentObject var store:AppStore; @State var step=0; var body:some View { VStack(spacing:20){ ProgressView(value:Double(step+1),total:2).padding(); if step==0 { Text("Hangi sınava hazırlanıyorsun?").font(.largeTitle.bold()); ForEach(store.exams){exam in Button{store.selectExam(exam)}label:{HStack{VStack(alignment:.leading){Text(exam.shortName).bold();Text(exam.name).font(.caption)};Spacer();if store.profile.selectedExamId==exam.id{Image(systemName:"checkmark.circle.fill")}}.padding().background(.thinMaterial,in:RoundedRectangle(cornerRadius:16))}.buttonStyle(.plain)} } else { Text("Planını kişiselleştir").font(.largeTitle.bold()); Picker("Tempo",selection:$store.profile.pace){Text("Hafif").tag("Hafif");Text("Dengeli").tag("Dengeli");Text("Yoğun").tag("Yoğun")}.pickerStyle(.segmented); TextField("Hedefin (örn. KPSS 85+)",text:$store.profile.targetLabel).textFieldStyle(.roundedBorder) }; Spacer(); Button(step==0 ? "Devam":"Planımı Oluştur"){if step==0{step=1}else{store.completeOnboarding()}}.buttonStyle(.borderedProminent).controlSize(.large).disabled(step==0 && store.profile.selectedExamId==nil) }.padding() } }

struct MainTabView:View{var body:some View{TabView{HomeView().tabItem{Label("Ana Sayfa",systemImage:"house.fill")};PlanView().tabItem{Label("Planım",systemImage:"calendar")};ProgressScreen().tabItem{Label("İlerleme",systemImage:"chart.bar.fill")};CoachView().tabItem{Label("Koç",systemImage:"bubble.left.and.bubble.right.fill")};ProfileView().tabItem{Label("Profil",systemImage:"person.crop.circle")}}}}

struct HomeView:View{@EnvironmentObject var store:AppStore;var body:some View{NavigationStack{ScrollView{VStack(alignment:.leading,spacing:18){Text("Merhaba, \(store.profile.name)").font(.largeTitle.bold());Text(store.selectedExam?.name ?? "").foregroundStyle(.secondary);HStack{Text("Genel ilerleme").bold();Spacer();Text("%\(Int(store.overallProgress*100))").bold()};ProgressView(value:store.overallProgress);Text("Bugünün planı").font(.title2.bold());ForEach(store.todayTasks){task in Button{store.toggleTask(task)}label:{HStack{Image(systemName:task.isDone ? "checkmark.circle.fill":"circle");VStack(alignment:.leading){Text(task.title).bold();Text(task.type).font(.caption)};Spacer()}.padding().background(Color(.secondarySystemBackground),in:RoundedRectangle(cornerRadius:16))}.buttonStyle(.plain)};GroupBox("Koç notu"){Text(store.coachMessage()).frame(maxWidth:.infinity,alignment:.leading)}}.padding()}.navigationTitle("NovaCoach").navigationBarTitleDisplayMode(.inline)}}}

struct PlanView:View{@EnvironmentObject var store:AppStore;var body:some View{NavigationStack{List{if let exam=store.selectedExam{ForEach(exam.sessions){session in Section(session.name){ForEach(session.subjects){subject in NavigationLink{TopicList(subject:subject)}label:{VStack(alignment:.leading){HStack{Text(subject.name);Spacer();Text("%\(Int(store.subjectProgress(subject)*100))")};ProgressView(value:store.subjectProgress(subject))}}}}}}}.navigationTitle("Planım")}}}
struct TopicList:View{@EnvironmentObject var store:AppStore;let subject:Subject;var body:some View{List(subject.topics){topic in Menu{ForEach(TopicState.allCases,id:\.self){state in Button(state.rawValue){store.markTopic(topic.id,state:state)}}}label:{HStack{Text(topic.name);Spacer();Text(store.progress[topic.id]?.state.rawValue ?? TopicState.notStarted.rawValue).font(.caption).foregroundStyle(.secondary)}}}.navigationTitle(subject.name)}}

struct ProgressScreen:View{@EnvironmentObject var store:AppStore;var body:some View{NavigationStack{List{Section("Genel"){LabeledContent("Müfredat ilerlemesi",value:"%\(Int(store.overallProgress*100))");LabeledContent("Bugünkü görev",value:"\(store.todayTasks.filter(\.isDone).count)/\(store.todayTasks.count)")};if let exam=store.selectedExam{ForEach(exam.sessions){s in ForEach(s.subjects){sub in HStack{Text(sub.name);Spacer();Text("%\(Int(store.subjectProgress(sub)*100))")}}}}}.navigationTitle("İlerleme")}}}
struct CoachView:View{@EnvironmentObject var store:AppStore;@State var note="";var body:some View{NavigationStack{VStack(alignment:.leading,spacing:18){GroupBox("Koç analizi"){Text(store.coachMessage()).frame(maxWidth:.infinity,alignment:.leading)};TextField("Koçuna not yaz",text:$note,axis:.vertical).textFieldStyle(.roundedBorder);Button("Planı Yeniden Hesapla"){if note.localizedCaseInsensitiveContains("yoğun"){store.profile.pace="Hafif"};store.generatePlan();note=""}.buttonStyle(.borderedProminent);Spacer()}.padding().navigationTitle("Koç")}}}
struct ProfileView:View{@EnvironmentObject var store:AppStore;var body:some View{NavigationStack{Form{Section("Hesap"){LabeledContent("Ad",value:store.profile.name);LabeledContent("E-posta",value:store.profile.email)};Section("Hazırlık"){LabeledContent("Sınav",value:store.selectedExam?.shortName ?? "-");LabeledContent("Hedef",value:store.profile.targetLabel);LabeledContent("Tempo",value:store.profile.pace)};Section{Button("Çıkış Yap",role:.destructive){store.logout()}}}.navigationTitle("Profil")}}}
